### ISSUE TITLE
Share API route to get game data files

### ISSUE THREAD

**Issue by joebobbio** [JRSKelvin/Honkai-Star-Rail-Repository#1]
Hi,

In your Genshin Impact manual download repository, you share the API route you use to get the game data download links in the README. However, this seems to be absent here. Could you possible share this route? I plan to implement update checking in an app of my own.

Thanks!

**Comment by JRSKelvin** [comment]
Thank You @joebobbio for your question. Unfortunately, I don't have an API at the moment, I got the data from my friend's message privately. I'll follow up to see if I can ask for the API. Thank you for the question.

**Comment by joebobbio** [comment]
Hi,
I found the URL myself, it is https://hkrpg-launcher-static.hoyoverse.com/hkrpg_global/mdk/launcher/api/resource?channel_id1&key=vplOVX8Vn7cwG8yb&launcher_id=35&sub_channel_id=0

**Comment by JRSKelvin** [comment]
Wow, Thank You Very Much @joebobbio for the link. May I copy the link for my repository and future repositories?

**Comment by joebobbio** [comment]
Sure!

**Comment by pha1n0q** [comment]
Is there any update for the HoYoPlay API which has the v2.3 download links?

**Comment by joebobbio** [comment]
Hi, the new API route for Star Rail is
https://sg-hyp-api.hoyoverse.com/hyp/hyp-connect/api/getGamePackages?launcher_id=VYTpXlbWo8
The formatting is slightly different, so the scraper will need to be
updated. For now though you can read through it yourself and grab the
download links you need.

**Comment by pha1n0q** [comment]
Thank you so much! I appreciate it <3
